### ISSUE TITLE
[Question] Usage within Mini App

### ISSUE THREAD

**Issue by coding-velociraptor** [thirdweb-example/telegram-mini-app#1]
Hey there,

thank you for providing such a detailed example for Telegram + Thirdweb Unity integration, and additional simplifications.

I created a Mini App based on this repository. I noticed that the BotFather asks for a direct link to the web app and also the InlineKeyboard for `webApp` takes an `url` pararmeter. Former can't contain any payload and latter might contain expired payload, if the Telegram user does not press the button before expiration. It seems like, one has to use the client side library to receive fresh credentials in the `initData` on web app load, then valid it on the backend to provide some JWT/payload. That's similar to the previous flow.

Am I missing something?

Thank you!

**Comment by coding-velociraptor** [comment]
P.S: https://github.com/thirdweb-example/telegram-mini-app/blob/main/telegram-bot/src/bot/start.ts#L28 expires after 10 minutes. A player would have to send `/start` again, righ?

**Comment by coding-velociraptor** [comment]
Related: Is it possible to use this example + the new `AuthProvider.Telegram` on the `InAppWallet` wallet? Can a user start on the Mini App, then log in on WebGL or mobile?

**Comment by gregfromstl** [comment]
Hey @coding-velociraptor that's correct, the user would have to click the button before it expires for authentication to work. You could adjust this expiration time, but its at your own risk given the security implications.

This example uses custom auth, which is separate from the built-in Telegram OAuth so they would not return the same wallet. This wallet isn't dependent on the telegram user for anything and is more flexible in how its generated.
